# Translations template for neutron.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the neutron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron 2015.1.dev472\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-11 06:13+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: neutron/policy.py:101
#, python-format
msgid ""
"Found deprecated policy rule:%s. Please consider upgrading your policy "
"configuration file"
msgstr ""

#: neutron/policy.py:159
#, python-format
msgid "Unable to find data type descriptor for attribute %s"
msgstr ""

#: neutron/quota.py:241
#, python-format
msgid "%s is already registered."
msgstr ""

#: neutron/agent/rpc.py:112
msgid "DVR functionality requires a server upgrade."
msgstr ""

#: neutron/agent/rpc.py:135
msgid "Tunnel synchronization requires a server upgrade."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:69
#: neutron/agent/securitygroups_rpc.py:175
msgid "Driver configuration doesn't match with enable_security_group"
msgstr ""

#: neutron/agent/securitygroups_rpc.py:127
msgid ""
"Security group agent binding currently not set. This should be set by the"
" end of the init process."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:202
msgid ""
"security_group_info_for_devices rpc call not supported by the server, "
"falling back to old security_group_rules_for_devices which scales worse."
msgstr ""

#: neutron/agent/dhcp/agent.py:117
#, python-format
msgid ""
"Unable to %(action)s dhcp for %(net_id)s: there is a conflict with its "
"current state; please check that the network and/or its subnet(s) still "
"exist."
msgstr ""

#: neutron/agent/dhcp/agent.py:127 neutron/agent/dhcp/agent.py:196
#, python-format
msgid "Network %s has been deleted."
msgstr ""

#: neutron/agent/dhcp/agent.py:213
#, python-format
msgid ""
"Network %s may have been deleted and its resources may have already been "
"disposed."
msgstr ""

#: neutron/agent/dhcp/agent.py:349
#, python-format
msgid ""
"%(port_num)d router ports found on the metadata access network. Only the "
"port %(port_id)s, for router %(router_id)s will be considered"
msgstr ""

#: neutron/agent/dhcp/agent.py:558 neutron/agent/l3/agent.py:1041
#: neutron/agent/metadata/agent.py:346
#: neutron/services/metering/agents/metering_agent.py:270
msgid ""
"Neutron server does not support state report. State report for this agent"
" will be disabled."
msgstr ""

#: neutron/agent/l3/agent.py:184
#, python-format
msgid ""
"l3-agent cannot check service plugins enabled at the neutron server when "
"startup due to RPC error. It happens when the server does not support "
"this RPC API. If the error is UnsupportedVersion you can ignore this "
"warning. Detail message: %s"
msgstr ""

#: neutron/agent/l3/agent.py:196
#, python-format
msgid ""
"l3-agent cannot check service plugins enabled on the neutron server. "
"Retrying. Detail message: %s"
msgstr ""

#: neutron/agent/l3/agent.py:307
#, python-format
msgid "Info for router %s were not found. Skipping router removal"
msgstr ""

#: neutron/agent/l3/router_info.py:176
#, python-format
msgid "Unable to configure IP address for floating IP: %s"
msgstr ""

#: neutron/agent/linux/dhcp.py:230
#, python-format
msgid "Failed trying to delete interface: %s"
msgstr ""

#: neutron/agent/linux/dhcp.py:238
#, python-format
msgid "Failed trying to delete namespace: %s"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:237
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:681
#, python-format
msgid "Attempted to get traffic counters of chain %s which does not exist"
msgstr ""

#: neutron/agent/linux/keepalived.py:424
msgid ""
"A previous instance of keepalived seems to be dead, unable to restart it,"
" a new instance will be spawned"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:336
#, python-format
msgid "Found not yet ready openvswitch port: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:339
#, python-format
msgid "Found failed openvswitch port: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:380
#, python-format
msgid "ofport: %(ofport)s for VIF: %(vif)s is not a positive integer"
msgstr ""

#: neutron/agent/metadata/agent.py:128
msgid "Server does not support metadata RPC, fallback to using neutron client"
msgstr ""

#: neutron/agent/metadata/agent.py:241
msgid ""
"The remote metadata server responded with Forbidden. This response "
"usually occurs when shared secrets do not match."
msgstr ""

#: neutron/api/api_common.py:102
#, python-format
msgid ""
"Invalid value for pagination_max_limit: %s. It should be an integer "
"greater to 0"
msgstr ""

#: neutron/api/extensions.py:544
#, python-format
msgid "Did not find expected name \"%(ext_name)s\" in %(file)s"
msgstr ""

#: neutron/api/extensions.py:552
#, python-format
msgid "Extension file %(f)s wasn't loaded due to %(exception)s"
msgstr ""

#: neutron/api/extensions.py:593
#, python-format
msgid "Extension %s not supported by any of loaded plugins"
msgstr ""

#: neutron/api/extensions.py:605
#, python-format
msgid "Loaded plugins do not implement extension %s interface"
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:72
#, python-format
msgid ""
"Unable to schedule network %s: no agents available; will retry on "
"subsequent port creation events."
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:85
#, python-format
msgid ""
"Only %(active)d of %(total)d DHCP agents associated with network "
"'%(net_id)s' are marked as active, so notifications may be sent to "
"inactive agents."
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:94
#, python-format
msgid ""
"Action %(action)s for network %(net_id)s could not complete successfully:"
" %(reason)s"
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:146
#: neutron/api/rpc/handlers/dhcp_rpc.py:210
#, python-format
msgid "Network %s could not be found, it might have been deleted concurrently."
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:279
#, python-format
msgid "Updating lease expiration is now deprecated. Issued  from host %s."
msgstr ""

#: neutron/cmd/sanity_check.py:74
msgid ""
"The user that is executing neutron can read the namespaces without using "
"the root_helper. Disable the use_helper_for_ns_read option to avoid a "
"performance impact."
msgstr ""

#: neutron/db/agents_db.py:101
#, python-format
msgid "%(agent_type)s agent %(agent_id)s is not active"
msgstr ""

#: neutron/db/agents_db.py:114
#, python-format
msgid "Configuration for agent %(agent_type)s on host %(host)s is invalid."
msgstr ""

#: neutron/db/agentschedulers_db.py:130
#, python-format
msgid ""
"Time since last %s agent reschedule check has exceeded the interval "
"between checks. Waiting before check to allow agents to send a heartbeat "
"in case there was a clock adjustment."
msgstr ""

#: neutron/db/agentschedulers_db.py:256
#, python-format
msgid ""
"Removing network %(network)s from agent %(agent)s because the agent did "
"not report to the server in the last %(dead_time)s seconds."
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:103
#, python-format
msgid ""
"Rescheduling router %(router)s from agent %(agent)s because the agent did"
" not report to the server in the last %(dead_time)s seconds."
msgstr ""

#: neutron/db/l3_dvrscheduler_db.py:298
msgid "No active L3 agents found for SNAT"
msgstr ""

#: neutron/db/l3_hamode_db.py:419
#, python-format
msgid "The router %(router_id)s is bound multiple times on the agent %(host)s"
msgstr ""

#: neutron/db/securitygroups_rpc_base.py:371
#, python-format
msgid "No valid gateway port on subnet %s is found for IPv6 RA"
msgstr ""

#: neutron/db/migration/alembic_migrations/heal_script.py:90
#, python-format
msgid "Ignoring alembic command %s"
msgstr ""

#: neutron/debug/debug_agent.py:121
#, python-format
msgid "Failed to delete namespace %s"
msgstr ""

#: neutron/notifiers/nova.py:76
msgid ""
"Authenticating to nova using nova_admin_* options is deprecated. This "
"should be done using an auth plugin, like password"
msgstr ""

#: neutron/notifiers/nova.py:232
msgid "Port ID not set! Nova will not be notified of port status change."
msgstr ""

#: neutron/notifiers/nova.py:288
#, python-format
msgid "Nova returned NotFound for event: %s"
msgstr ""

#: neutron/notifiers/nova.py:306
#, python-format
msgid "Nova event: %s returned with failed status"
msgstr ""

#: neutron/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)r run outlasted interval by %(delay).2f sec"
msgstr ""

#: neutron/openstack/common/service.py:355
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:582
#, python-format
msgid "vlan_id %(vlan)s on physical network %(network)s not found"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:659
#, python-format
msgid "vxlan_id %s not found"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:174
msgid "No policy profile populated from VSM"
msgstr ""

#: neutron/plugins/embrane/agent/operations/router_operations.py:96
#, python-format
msgid "The router %s had no physical representation,likely already deleted"
msgstr ""

#: neutron/plugins/embrane/agent/operations/router_operations.py:125
#, python-format
msgid "Interface %s not found in the heleos back-end,likely already deleted"
msgstr ""

#: neutron/plugins/hyperv/agent/utilsfactory.py:61
msgid ""
"V1 virtualization namespace no longer supported on Windows Server / "
"Hyper-V Server 2012 R2 or above."
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:428
#, python-format
msgid "Ignoring admin_state_up=False for router=%r.  Overriding with True"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:84
msgid "VXLAN is enabled, a valid local_ip must be provided"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:98
msgid "Invalid Network ID, will lead to incorrect bridgename"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:105
msgid "Invalid VLAN ID, will lead to incorrect subinterface name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:112
msgid "Invalid Interface ID, will lead to incorrect tap device name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:121
#, python-format
msgid "Invalid Segmentation ID: %s, will lead to incorrect vxlan device name"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:521
#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:557
#, python-format
msgid ""
"Option \"%(option)s\" must be supported by command \"%(command)s\" to "
"enable %(mode)s mode"
msgstr ""

#: neutron/plugins/linuxbridge/agent/linuxbridge_neutron_agent.py:551
msgid ""
"VXLAN muticast group must be provided in vxlan_group option to enable "
"VXLAN MCAST mode"
msgstr ""

#: neutron/plugins/ml2/driver_context.py:184
#, python-format
msgid "Could not expand segment %s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:520
#, python-format
msgid ""
"In _notify_port_updated(), no bound segment for port %(port_id)s on "
"network %(network_id)s"
msgstr ""

#: neutron/plugins/ml2/plugin.py:758
msgid "A concurrent port creation has occurred"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1248
#, python-format
msgid "Port %(port)s updated up by agent not found"
msgstr ""

#: neutron/plugins/ml2/plugin.py:1280
#, python-format
msgid "Port %s not found during update"
msgstr ""

#: neutron/plugins/ml2/rpc.py:70
#, python-format
msgid "Device %(device)s requested by agent %(agent_id)s not found in database"
msgstr ""

#: neutron/plugins/ml2/rpc.py:79
#, python-format
msgid ""
"Device %(device)s requested by agent %(agent_id)s on network "
"%(network_id)s not bound, vif_type: %(vif_type)s"
msgstr ""

#: neutron/plugins/ml2/drivers/helpers.py:141
#, python-format
msgid ""
"Allocate %(type)s segment from pool failed after %(number)s failed "
"attempts"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_agent.py:75
#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:116
#, python-format
msgid "Attempting to bind with dead agent: %s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:131
#, python-format
msgid "No flat network found on physical network %s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:106
msgid "Gre allocations were already created."
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:160
#, python-format
msgid "Gre endpoint with ip %s already exists"
msgstr ""

#: neutron/plugins/ml2/drivers/type_tunnel.py:178
#, python-format
msgid "%(type)s tunnel %(id)s not found"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:257
#, python-format
msgid "No vlan_id %(vlan_id)s found on physical network %(physical_network)s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:171
#, python-format
msgid "Vxlan endpoint with ip %s already exists"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:66
#, python-format
msgid "Create network postcommit failed for network %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:76
#, python-format
msgid "Create subnet postcommit failed for subnet %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:90
#, python-format
msgid "Create port postcommit failed for port %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_sync.py:109
#, python-format
msgid "Add interface postcommit failed for port %s"
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/mech_driver.py:108
#, python-format
msgid "unable to modify mac_address of ACTIVE port %s"
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/mech_driver.py:161
msgid "Unable to retrieve the agent ip, check the agent configuration."
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/mech_driver.py:167
#, python-format
msgid "Port %(port)s updated by agent %(agent)s isn't bound to any segment"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:110
msgid "No Token, Re-login"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:159
#, python-format
msgid ""
"L2 agent could not get DVR MAC address at startup due to RPC error.  It "
"happens when the server does not support this RPC API.  Detailed message:"
" %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:185
#, python-format
msgid ""
"L2 agent could not get DVR MAC address from server. Retrying. Detailed "
"message: %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:483
#, python-format
msgid "Action %s not supported"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:904
#, python-format
msgid ""
"Creating an interface named %(name)s exceeds the %(limit)d character "
"limitation. It was shortened to %(new_name)s to fit."
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1064
#, python-format
msgid "VIF port: %s has no ofport configured, and might not be able to transmit"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1181
#, python-format
msgid "Device %s not defined on plugin"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1336
#, python-format
msgid "Invalid remote IP: %s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1379
msgid "OVS is restarted. OVSNeutronAgent will reset bridges and recover ports."
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1383
msgid ""
"OVS is dead. OVSNeutronAgent will keep running and checking OVS status "
"periodically."
msgstr ""

#: neutron/plugins/sriovnicagent/eswitch_manager.py:146
#: neutron/plugins/sriovnicagent/eswitch_manager.py:159
#, python-format
msgid "Cannot find vf index for pci slot %s"
msgstr ""

#: neutron/plugins/sriovnicagent/eswitch_manager.py:282
#, python-format
msgid "device pci mismatch: %(device_mac)s - %(pci_slot)s"
msgstr ""

#: neutron/plugins/sriovnicagent/pci_lib.py:124
#, python-format
msgid "Cannot find vfs %(vfs)s in device %(dev_name)s"
msgstr ""

#: neutron/plugins/sriovnicagent/pci_lib.py:140
#, python-format
msgid "failed to parse vf link show line %(line)s: for %(device)s"
msgstr ""

#: neutron/scheduler/dhcp_agent_scheduler.py:83
#: neutron/scheduler/dhcp_agent_scheduler.py:91
msgid "No more DHCP agents"
msgstr ""

#: neutron/scheduler/dhcp_agent_scheduler.py:122
#, python-format
msgid "DHCP agent %s is not active"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:156
#, python-format
msgid "No routers compatible with L3 agent configuration on host %s"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:181
msgid "No active L3 agents"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:193
#, python-format
msgid "No L3 agents can host the router %s"
msgstr ""

#: neutron/services/provider_configuration.py:58
#, python-format
msgid ""
"The configured driver %(driver)s has been moved, automatically using "
"%(new_driver)s instead. Please update your config files, as this "
"automatic fixup will be removed in a future release."
msgstr ""

